### ISSUE TITLE
Configuration Roles for 8.2 Update 3

### ISSUE THREAD

**Issue by AshleyMallia** [AlenPelin/ConfigurationRoles822#1]
These fails are very useful.
Do you intend to release comparable config files for Sitecore 8.2 Update 3 any time soon?

**Comment by AlenPelin** [comment]
The difference is tiny - just two files:
[Include file changes in 823.zip](https://github.com/AlenPelin/ConfigurationRoles822/files/972605/Include.file.changes.in.823.zip)

**Comment by AlenPelin** [comment]
But I haven't tested them so far.

**Comment by AshleyMallia** [comment]
Thanks
